name: Run Unit Tests with Jest

on:
  push:
    branches:
      - main
      - master
      - hono-rewrite
  pull_request:
    branches:
      - main
      - master
      - hono-rewrite

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run Jest tests
        run: pnpm test
